version: '3'

services:

  order-service:
    build:
      context: order_service/
      dockerfile: Dockerfile
    depends_on:
      - database
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=order_service.settings
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./order_service:/app
    ports:
      - "8000:8000"

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: order_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  product-service:
    image: rodolpheche/wiremock:2.23.2-alpine
    command: --verbose
    volumes:
      - ./wiremock/product-service/stubs:/home/wiremock
    ports:
      - "8081:8080"

  user-service:
    image: rodolpheche/wiremock:2.23.2-alpine
    command: --verbose
    volumes:
      - ./wiremock/user-service/stubs:/home/wiremock
    ports:
      - "8082:8080"

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=hellofresh
      - RABBITMQ_DEFAULT_PASS=food
    ports:
      - "5672:5672"
      - "15672:15672"
